name: Dependency Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Download Dependency-Check
        run: |
          wget https://github.com/jeremylong/DependencyCheck/releases/download/v9.1.0/dependency-check-9.1.0-release.zip
          unzip dependency-check-9.1.0-release.zip -d $HOME
          chmod +x $HOME/dependency-check/bin/dependency-check.sh

      - name: Cache Dependency-Check data
        uses: actions/cache@v3
        with:
          path: ~/.dependency-check
          key: ${{ runner.os }}-dependency-check


      - name: Debug NVD API Key
        run: |
          if [ -z "${{ secrets.NVD_API_KEY }}" ]; then
            echo "NVD_API_KEY is missing or empty!"
            exit 1
          else
            echo "NVD_API_KEY is set (hidden)"
          fi

      - name: Test NVD API
        run: |
          curl -H "Accept: application/json" \
               -H "apiKey: 9d415b21-6410-464a-89a8-42ab22731476" \
               "https://services.nvd.nist.gov/rest/json/cves/2.0?cpeName=cpe:2.3:o:microsoft:windows_10:1607:*:*:*:*:*:*:*" | jq .

      - name: Run Dependency Check (try API, fallback to noupdate)
        run: |
          $HOME/dependency-check/bin/dependency-check.sh \
            --project "${{ github.event.repository.name }}" \
            --scan . \
            --format "HTML" \
            --out reports/ \
            --nvdApiKey 9d415b21-6410-464a-89a8-42ab22731476 \
            --nvdApiDelay 60000 \
            --cveValidForHours 24 \
            --update


          echo "=== Reports directory contents ==="
          ls -R reports/
          
      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports/
